### ISSUE TITLE
all posts not being copied over to /_site volume

### ISSUE THREAD

**Issue by normdoow** [BretFisher/jekyll-serve#11]
I have my own jekyll site that I am trying to develop with using the jekyll-serve image. I copied over the docker-compose.yaml 

```
version: '2'

services:
  jekyll:
    build: ./
    volumes:
      - .:/site
    ports:
      - '8080:4000'
```
I updated the image to be build with my current directory cause I wanted to add a little change to the Dockerfile. Here is the Dockerfile...
```
FROM bretfisher/jekyll-serve

RUN gem install jekyll-paginate
RUN gem install jekyll-archives
```
Then I just do `docker-compose up` to run it. The site seems to be created correctly. I can go to the main page at localhost:8080 but if I try to go to any of the posts it isn't found. and the url looks like this `http://0.0.0.0:4000/jekyll/tutorial/2018/01/11/quick-start-guide.html` Instead of localhost:8080 it adds the ip and port that is from the inside the container.

I also noticed inside the _site director that gets copied as the volume, that there aren' any of my posts in there. Seems like that is an issue with the volumes.

Is there something I am doing wrong here? Or am I trying to use the image in an incorrect way?

Thanks!

**Comment by BretFisher** [comment]
First you'd need to see if bind-mounts are even working in your container. Once it's running, do a `docker-compose exec jekyll bash` and `ls /site` to see if you're getting the files you expect from the mount.

**Comment by normdoow** [comment]
Yep, I am getting what I expect!

<img width="679" alt="screen shot 2018-12-12 at 7 56 16 am" src="https://user-images.githubusercontent.com/21371266/49871220-9e4c3c80-fde3-11e8-896b-c7fa47df0c1e.png">

I can see all the posts there under _posts. 
Another note. when hosting with github pages all of the post paths and everything works so the docker setup is somehow messing that up.

**Comment by BretFisher** [comment]
It all works, so it must be something with your Jekyll config or site setup.
