### ISSUE TITLE
Don't overwrite host/port information specified in _config

### ISSUE THREAD

**Issue by j6k4m8** [BretFisher/jekyll-serve#13]
There is no way to use this serve script out of the box without running on a machine where 0.0.0.0:4000 is the desired endpoint.

Though you can of course run this with a custom build line (`docker run... bundle exec jekyll serve`) it would be nice to support this from scratch!

**Comment by j6k4m8** [comment]
...i....don't remember why I asked this...
I feel like I must have had a good reason..?

**Comment by BretFisher** [comment]
😜
