### ISSUE TITLE
question about enable https

### ISSUE THREAD

**Issue by xiao1201** [BretFisher/jekyll-serve#15]
hi thanks for the jekyll image it's running great, now i want to enable https for my blog on a vps, so does this jekyll use nginx or webrick as web server? and how to configure to enbale https? thank you very much.

**Comment by BretFisher** [comment]
This is just an standard Jekyll install (see Dockerfile). I recommend you research the Jekyll docs for those answers. Also, check the README as it's meant for local dev, not servers or https.

**Comment by xiao1201** [comment]
thank you. issue closed for worthless q
