### ISSUE TITLE
Error when changing template in Gemfile

### ISSUE THREAD

**Issue by gilsonoliveiraj** [BretFisher/jekyll-serve#2]
Sorry to bother.

When trying to change the theme of Jekyll site, by replacing

`gem "minima", "~> 2.0"
`
by
`gem "github-pages", group: :jekyll_plugins
`
and running:
`docker run -p 80:4000 --rm -v $(pwd):/site bretfisher/jekyll-serve
`
I'm getting the have the following output:
```
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 3.7.3)

  In Gemfile:
    github-pages was resolved to 4, which depends on
      jekyll (= 1.1.2)

    jekyll-feed (~> 0.6) was resolved to 0.9.3, which depends on
      jekyll (~> 3.3)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
I tried to run the bundle update command in the end of the container run command but it didn't work.

Any help is highly appreciated.

Regards,
Gilson

**Comment by BretFisher** [comment]
Hey there, sounds like you need to ask that in a jekyll support site. I only changed a few things from the default docker jekyll image so I doubt it's anything to do with my repo :)

**Comment by gilsonoliveiraj** [comment]
Hi, that's ok. Should be something with the new version of Jekyll being compatible with github pages themes.
