### ISSUE TITLE
Add --future and --draft flags to Dockerfile.serve

### ISSUE THREAD

**Issue by eduherminio** [BretFisher/jekyll-serve#22]
I'd find it useful to have `--future` and `--draft` Jekyll flags to in `Dockerfile.serve`.

**Comment by tadeobarranco** [comment]
@eduherminio for the meanwhile you can add the `show_drafts` bool flag in your `_config.yml` file, I did it and it works.

**Comment by eduherminio** [comment]
> @eduherminio for the meanwhile you can add the `show_drafts` bool flag in your `_config.yml` file, I did it and it works.

Thanks Tadeo!
Although having that configuration in a `docker-compose` file works better for me to prevent committing such a change accidentally.

```dockerfile
version: "2.4"

services:
  jekyll:
    image: my_local_image_based_on_bretfisher/jekyll-serve
    command: bundle exec jekyll serve --force_polling --future --draft -H 0.0.0.0 -P 4000
    volumes:
      - .:/site
    ports:
      - "8080:4000"
```

I had it already set up due to using a custom image based on `bretfisher/jekyll-serve` (that's a longer story), so there's really no overhead for me, but I just though that having those flags on by default could be a 'nice to have'.

**Comment by BretFisher** [comment]
These are good options for documentation (if I had any :P) but I don't think they should be defaults (they aren't default in the jekyll command, so why should that change for docker 😄 )

Also, remember if you're just forking this repo, you can always add your own override file ([docker-compose.override.yml](https://docs.docker.com/compose/extends/)) to change the CMD (like you show above) without editing the original docker-compose.yml

**Comment by eduherminio** [comment]
Fair enough @BretFisher!

I'm not forking this repo, just added a `docker-compose.yml` to mine, but thanks for pointing me to `docker-compose.override.yml`, good to have it in mind.
