### ISSUE TITLE
No backwards compatibility with GH Pages

### ISSUE THREAD

**Issue by kad-wenner** [BretFisher/jekyll-serve#27]
Hi,

We have been using this image for quite a while now until it suddenly broke down a few days ago. This ultimately has to do with us using this image with Github Pages to serve our website. Upgrading to Ruby 3.0 broke an underlying dependency.

(see this thread for an example: https://talk.jekyllrb.com/t/error-no-implicit-conversion-of-hash-into-integer/5890)

For us it was an easy fix to roll back to Ruby 2.7 (after figuring out what went wrong), but it might be a good idea to add a backward compatible tag on docker hub using Ruby 2.7 for subsequent users running into the same issue. 

Cheers, 

Rob

**Comment by BretFisher** [comment]
OK thanks for the feedback. I think I'm moving the latest back to ruby 2.x for now, and I'll add some new tags to help you avoid major updates to Ruby or Jekyll.  I'll ping back here once that's done.

**Comment by BretFisher** [comment]
OK latest images are now fixed to `ruby:2-alpine` and updated monthly to keep them on fresh ruby-2 and Jekyll versions.
