### ISSUE TITLE
Both images seem equal

### ISSUE THREAD

**Issue by jochenjonc** [BretFisher/jekyll-serve#41]
Hi @BretFisher,

I've been trying to use the docker images on my Synology NAS, but every time I start the bretfisher/jekyll I get the following in the console.

```
NOTE: hmm, I don't see a Gemfile so I don't think there's a jekyll site here
Either you didn't mount a volume, or you mounted it incorrectly.
Be sure you're in your jekyll site root and use something like this to launch

docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

NOTE: To create a new site, you can use the sister image bretfisher/jekyll like:

docker run -v $(pwd):/site bretfisher/jekyll new .
```

I noticed that both images have the same size also. 

Do you have any clue?

Regards,

Jochen

**Comment by BretFisher** [comment]
What command are you using to start it? What's in that directory? It will get that error if it doesn't see the Gemfile in the bind-mount.

**Comment by BretFisher** [comment]
Oh I see, the CMD is the same in both images, and is a bug I created by moving to GitHub Actions without specifying the build stage. This but doesn't affect `bretfisher/jekyll-serve`, only the default behavior of `bretfisher/jekyll`. Give me a few to fix this.

**Comment by BretFisher** [comment]
OK this should be fixed. Feel free to reopen if you have more issues or questions.
