### ISSUE TITLE
not working anymore on raspbian

### ISSUE THREAD

**Issue by manuroot72** [BretFisher/jekyll-serve#62]
Since last update of image, i cannot start my container:
/usr/local/lib/ruby/2.7.0/rubygems/specification.rb:106:in `initialize': Operation not permitted - clock_gettime (Errno::EPERM)
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:106:in `now'
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:106:in `<class:Specification>'
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:39:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems.rb:1417:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems.rb:1417:in `<module:Gem>'
	from /usr/local/lib/ruby/2.7.0/rubygems.rb:115:in `<top (required)>'
	from <internal:gem_prelude>:1:in `require'
	from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
Ist on raspbian 

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
pi@raspberry-pi4:/DATA/

Do you have an idea to resolve this problem?

**Comment by manuroot72** [comment]
i ve added --privileged: true to the docker-compose.yml or with the docker run:
docker run -p 4000:4000 --privileged -v $(pwd):/site bretfisher/jekyll-serve
it seems to work

**Comment by BretFisher** [comment]
Reopening this issue to see if others have it. Running `--privileged` shouldn't be required. are you sure your host file permissions were set so that the container could write to that location?
