### ISSUE TITLE
Why docker-compose and docker run ( help )

### ISSUE THREAD

**Issue by Vctrsnts** [BretFisher/jekyll-serve#68]
Hello.

I am trying to use its container, but I have a couple of doubts when it comes to using it.

  * Why put the "docker-compose" if the next thing you do is a "docker-run" (that's what I see if I check the entrypoint.sh)

  * What is the difference between jekyll and jekyll-server? because in your documentation I don't see any difference.

  * In its details, you explain "_it will mount your current path into the containers / site, bundle install before running jekyll serve to, serve it at http: // <docker-host>: 4000_". But my question is how are you going to "bundle" the container if it doesn't work until you do a "docker run" (all this using the docker-compose).

Thanks if you can help me

**Comment by BretFisher** [comment]
1. The README shows both ways to use the images. `docker run` or `docker-compose up` both work, so it's up to you
2. `jekyll-serve` starts a server to run an existing site. `jekyll` image can be used to create a site, or run other jekyll commands when you don't want to run the server by default. The are both mostly the same. You can see in the [Dockerfile](https://github.com/BretFisher/jekyll-serve/blob/main/Dockerfile) that all `jekyll-serve` does is add a entrypoint script and change the CMD.
3. If you're running the `jekyll-serve` image, it has a entrypoint script that will run bundle before the server starts.
