### ISSUE TITLE
Changing theme seems to break jekyll?

### ISSUE THREAD

**Issue by Waldorf3** [BretFisher/jekyll-serve#73]
So I run the first docker command to create the site, then edit the _config.yml file to change the theme, then start the docker-compose.yml - but now it breaks.

I am running a lot of other docker containers in my homelab, but never had to run two different as here so I probably don't quite understand how they relate to each other? Help?

**Comment by Waldorf3** [comment]
So I run the first docker command to create the site, then edit the _config.yml file to change the theme, then start the docker-compose.yml - but now it breaks. 

I am running a lot of other docker containers in my homelab, but never had to run two different as here so I probably don't quite understand how they relate to each other?  Help?

**Comment by BretFisher** [comment]
Hmm, not sure. I don't know what commands you are running, or the exact error. I assume it's a jekyll issue, so I'd ask if you are able to get it working without docker.

**Comment by Waldorf3** [comment]
I'm just following your instructions to setup the site, that works ok. Then I change the theme in the _config.yml file like I explained, but when I up the docker-compose.yml again it throws an error.

**Comment by BretFisher** [comment]
What's the exact error?
Do you have a repo that I can reproduce the problem with?

**Comment by derek-adair** [comment]
@Waldorf3 You'll have better luck asking questions in forums like this if you provide more context.  Generally speaking when asking for help from complete strangers it's good to provide *at least* the error you are running into, along with the relevant code.  It's likely you have an error in your _config.yml or your theme.

> I am running a lot of other docker containers in my homelab, but never had to run two different as here so I probably don't quite understand how they relate to each other? Help?

While it is almost certainly not the issue - you should check out the documentation on [Networking within Docker](https://docs.docker.com/network/).... as it COULD be... depending on your error.

Cheers!

**Comment by aaronwatson** [comment]
If I had to guess, it sounds like you need to install the theme. If it is gem-based, follow the instructions[ here](https://jekyllrb.com/docs/themes/#installing-a-theme).
