### ISSUE TITLE
[Question] What other issues did you find with Ruby 3.0?

### ISSUE THREAD

**Issue by derek-adair** [BretFisher/jekyll-serve#74]
Hello!

I'm considering swapping to this image from the official image due to it sort of idling out.  (e.g. they have STILL not added webrick manually as a dependency).

What other issues have you identified with Ruby 3.0?

Sidebar - how actively maintained is this project?

**Comment by derek-adair** [comment]
For what it's worth very shortly after i posted this, I ran into yet *another* dep issue in the official jekyll image, booted this up and it worked.

**Comment by BretFisher** [comment]
I'm only aware of the webrick issue with 3.x.
It's maintained by me, but please see the readme warning :)

**Comment by derek-adair** [comment]
Ahhh.  It was reverted to 2.x BECAUSE webrick.  I thought there were other issues.  Cheers.
