### ISSUE TITLE
Error when running  `bretfisher/jekyll --build`

### ISSUE THREAD

**Issue by scottyab** [BretFisher/jekyll-serve#78]
Hi @BretFisher, Thanks for the efforts and this repo it's helped me get a simple Jekyll blog running in no time. I was planning to use the `bretfisher/jekyll` Docker image in a GitHub Action to process the .md files of my blog into HTML. I am having issues with that but in trying to isolate the issue I found I cannot even call build locally 

 `docker run -v $(pwd):/site bretfisher/jekyll --build`  I get the following error? 

```
/usr/local/bundle/gems/bundler-2.3.23/lib/bundler/definition.rb:508:in `materialize': Could not find minima-2.5.1, jekyll-feed-0.17.0, jekyll-seo-tag-2.8.0, rexml-3.2.5 in locally installed gems (Bundler::GemNotFound)
	from /usr/local/bundle/gems/bundler-2.3.23/lib/bundler/definition.rb:187:in `specs'
	from /usr/local/bundle/gems/bundler-2.3.23/lib/bundler/definition.rb:244:in `specs_for'
	from /usr/local/bundle/gems/bundler-2.3.23/lib/bundler/runtime.rb:18:in `setup'
	from /usr/local/bundle/gems/bundler-2.3.23/lib/bundler.rb:162:in `setup'
	from /usr/local/bundle/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	from /usr/local/bundle/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:23:in `load'
	from /usr/local/bundle/bin/jekyll:23:in `<main>'
```

The jekyll-serve image works a-ok, I'm sure I'm missing something simple. Thanks

**Comment by BretFisher** [comment]
OK so the `bretfisher/jekyll` image only runs one-off jekyll commands, but doesn't run a `bundle install` first, which is what you need.  `bretfisher/jekyll-serve` image does have the ENTRYPOINT run the `bundle install` so it could maybe work fine for you...

But there are likely much better Jekyll Actions out there. This repo and example predate Actions.

[https://github.com/marketplace?type=actions&query=jekyll](https://github.com/marketplace?type=actions&query=jekyll)

**Comment by scottyab** [comment]
I had wanted to use your image so I was being consistent between development and CI. That said I've switched to using [this](https://github.com/marketplace/actions/build-jekyll) specific Github Action for Jeykell, thanks @BretFisher
