### ISSUE TITLE
Live reload?

### ISSUE THREAD

**Issue by pdavisonreiber** [BretFisher/jekyll-serve#79]
Is there a way I can run this with live reload enabled, so that changes to the files in the directory trigger the site to regenerate?

**Comment by BretFisher** [comment]
Jekyll file watching is built-in. With Docker Desktop, if I go into my Jekyll sites directory and run the image as the `README.md` suggests, and then make a change in a `_posts` file and save it, I can see the Jekyll logs in Docker re-build my site and all I need to do is refresh the browser.

What's your experience? If different, please describe your setup in detail so we can try to reproduce.
