### ISSUE TITLE
(question) docker jekyll-serve read _config.yml

### ISSUE THREAD

**Issue by Vctrsnts** [BretFisher/jekyll-serve#86]
Hello,

First of all, sorry if my question is not a problem with your image and it is a jekyll problem that I have to solve on my own.

I use your **jekyll-serve image**, but I have a question about how it works locally and then upload the result to **github**.

The question is the following, I have configured the `_config.yml -> url` with my web address but when executing the image the `feed.xml` file maintains the following address **http://0.0.0.0:4000** and there is no way to change that address (no matter how many changes you make to the configuration file and how many times you reboot the image). It's like it ignores the `_config.yml` file.

But on the other hand, if I execute from within the image `bundle exec jekyll build --watch` all the files are regenerated correctly, 0ncluding the `feed.xml`, but this time with the correct address (the one that I have informed in the url of `_config. yml` ).

This is where I have the doubt, that it has to be done like this (because of the operation of the image) or is it that the image does not read the configuration file `_config.yml` when it starts.

Thank you very much for all your work.

**Comment by BretFisher** [comment]
Sorry that's a Jekyll question that I know nothing about.  The `jekyll-serve` [image runs](https://github.com/BretFisher/jekyll-serve/blob/61a2d58cc372dbda6702ee54a98be0cd5c6d6f4a/Dockerfile#L27) `jekyll serve` and your doing a `jekyll build`. Maybe there's a difference there.
