### ISSUE TITLE
can you release a updated version of jekyll-serve to docker hub?

### ISSUE THREAD

**Issue by silverhikari** [BretFisher/jekyll-serve#87]
when using these docker images i noticed that the Jekyll-serve image is far outdated compared to the base Jekyll image which seems to be causing a bundler mismatch when running jekyll-serve.

P.S: you might want to add "" around the pwd variable in the example commands as using it when in a directory with a space will cause issues with the files not being generated when running new.

**Comment by BretFisher** [comment]
OK I just merged a PR that I think fixes this image update issue. Thanks for the heads up.
