### ISSUE TITLE
A word of praise

### ISSUE THREAD

**Issue by alexyans** [BretFisher/jekyll-serve#88]
I just wanted to thank you. Being on Apple M1 it is not easy to make jekyll work locally, and the dev server from the official Docker image does not work for me either (debugging alpine is a pain). Your image worked perfectly 😗 👌

**Comment by BretFisher** [comment]
THANKS FOR THE THANKS!

![](https://media.giphy.com/media/ukJ4Gueb2QgUHcvjro/giphy.gif)
